config/routes.rb
Rails.application.routes.draw do
  get 'posts/index' 
  get 'posts/new'
  get 'posts/create'
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :content, :image_url, presence: true
    before_save :remove_word

    def remove_word
        self.content = self.content.remove(' spoiler')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  def create
    @post = Post.create(title: params[:title], image_url: params[:image_url], content: params[:content])
  end
  def dashboard
    @post = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class= "container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/create.html.erb
<div class= "mt-5">
    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
            <% @post.errors.full_messages.each do |error| %>
                <li><%= error %></li>
            <% end %>
            </ul>
            <button type= "button"class="btn btn-dark btn-sm mt-3"><%= link_to 'Back', posts_new_path %></button>
        </div>
        <% else %>
        <strong>Título:</strong>
        <p><%= @post.title %></p>
        <strong>Imagen:</strong>
        <p><%= image_tag @post.image_url%></p>
        <strong>Contenido:</strong>
        <p><%= @post.content %></p>
        <strong>Fecha creación:</strong>
        <p><%= @post.created_at %></p>

        <button type= "button"class="btn btn-dark btn-sm mt-3"><%= link_to 'Back', root_path %></button>
    <% end %>

</div>

app/views/posts/index.html.erb
<h1 class= "my-4">Posts</h1>

<button type="button" class="btn btn-danger btn-sm my-3 ml-auto"><%= link_to 'New Post', posts_new_path %></button>

<table class="table table-bordered">
    <thead class="bg-danger text-white">
        <tr>
            <th>Título</th>
            <th>Fecha creación</th>
            <th>Imagen</th>
            <th>Contenido</th>
        </tr>
    </thead> 
    <% @posts.present? && @posts.each do |post|%>
        <tr>
            <td><%= post.title%></td>
            <td><%= post.created_at%></td>
            <td><%=image_tag post.image_url%></td>
            <td><%= post.content%></td>
        </tr>
    <% end %>
</table>

app/views/posts/new.html.erb
<h1 class="mt-3 mb-4">Create a new post</h1>

<form method="get" action="/posts/create" id="create_posts">
    <label for="title">Titulo</label>
    <input name="title" class="form-control">

    <label for="image_url">Imagen</label>
    <input type="text" name="image_url" class="form-control">

    <label for="content">Contenido</label>
    <textarea name="content" class="form-control"></textarea>
    
    <button type= "submit"class="btn btn-danger btn-sm mt-3">Enviar</button>
    <button type= "button"class="btn btn-dark btn-sm mt-3"><%= link_to 'Back', root_path %></button>
</form>